[build]
  functions = "netlify/functions"
  publish = "build" 

[functions]
  external_node_modules = ["express", "cors", "dotenv", "emailjs-com"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/express-server/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200


